-- search-index
CREATE TABLE public.search_index (
  search_index_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_index_public_id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_public_id uuid NOT NULL REFERENCES public.events(event_public_id) ON DELETE CASCADE,
  content text,
  embedding vector(512),
  fts tsvector GENERATED ALWAYS AS (to_tsvector('japanese', content)) STORED
);

CREATE INDEX idx_search_index_embedding ON public.search_index USING hnsw (embedding vector_cosine_ops);
CREATE INDEX idx_search_index_fts ON public.search_index USING gin (fts);


-- data insart
INSERT INTO public.search_index (event_public_id, content)
SELECT
  event_public_id,
  (
    name || ' ' || 
    COALESCE(caption, '') || ' ' || 
    COALESCE(description, '') || ' ' || 
    COALESCE((
      SELECT string_agg(p->>'name', ' ') 
      FROM jsonb_array_elements(performers) AS p
    ), '') || ' ' ||
    COALESCE(organization->>'name', '')
  ) as content
FROM mv_event_details
ON CONFLICT DO NOTHING;