--------------------------------------------------------------------------------
-- Event Time Table (イベント時間)
--------------------------------------------------------------------------------
CREATE TABLE public.event_time (
  time_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  event_id BIGINT NOT NULL REFERENCES public.event(event_id) ON DELETE CASCADE,

  start_time TIME(0) NOT NULL,
  end_time TIME(0) NOT NULL,

  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,

  CONSTRAINT event_time_external_id_unique UNIQUE (id),
  CONSTRAINT check_start_time_no_seconds CHECK (EXTRACT(SECOND FROM start_time) = 0),
  CONSTRAINT check_end_time_no_seconds CHECK (EXTRACT(SECOND FROM end_time) = 0)
);

--------------------------------------------------------------------------------
-- Index
--------------------------------------------------------------------------------
CREATE INDEX idx_event_time_event_id
ON public.event_time (event_id);

CREATE INDEX idx_event_time_start_time
ON public.event_time (start_time);

--------------------------------------------------------------------------------
-- TimeStamp
--------------------------------------------------------------------------------
CREATE TRIGGER set_timestamp  
  BEFORE UPDATE ON public.event_time 
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_set_timestamp();

--------------------------------------------------------------------------------
-- RLS
--------------------------------------------------------------------------------
ALTER TABLE public.event_time ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
  ON public.event_time 
  FOR SELECT TO public USING (true);