--------------------------------------------------------------------------------
-- Event Tag Table (イベントタグ)
--------------------------------------------------------------------------------
CREATE TABLE public.event_tag (
  event_tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id UUID NOT NULL DEFAULT gen_random_uuid(),

  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,

  CONSTRAINT event_tag_external_id_unique UNIQUE (id)
);

--------------------------------------------------------------------------------
-- TimeStamp
--------------------------------------------------------------------------------
CREATE TRIGGER set_timestamp 
  BEFORE UPDATE ON public.event_tag 
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_set_timestamp();

--------------------------------------------------------------------------------
-- RLS
--------------------------------------------------------------------------------
ALTER TABLE public.event_tag ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
  ON public.event_tag 
  FOR SELECT TO public USING (true);