--------------------------------------------------------------------------------
-- Venue Table (会場)
--------------------------------------------------------------------------------
CREATE TABLE public.venue (
  venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id UUID NOT NULL DEFAULT gen_random_uuid(),

  name TEXT NOT NULL,
  description TEXT,
  capacity INTEGER,
  floor INTEGER,
  map_latitude DOUBLE PRECISION,
  map_longitude DOUBLE PRECISION,
  google_place_id TEXT,

  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,

  CONSTRAINT venue_external_id_unique UNIQUE (id)
);

--------------------------------------------------------------------------------
-- Index
--------------------------------------------------------------------------------
CREATE INDEX idx_venue_name
ON public.venue (name);

--------------------------------------------------------------------------------
-- TimeStamp
--------------------------------------------------------------------------------
CREATE TRIGGER set_timestamp 
  BEFORE UPDATE ON public.venue 
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_set_timestamp();

--------------------------------------------------------------------------------
-- RLS
--------------------------------------------------------------------------------
ALTER TABLE public.venue ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
  ON public.venue
  FOR SELECT TO public USING (true);