--------------------------------------------------------------------------------
-- Performer Table (発表者)
--------------------------------------------------------------------------------
CREATE TYPE public.performer_type AS ENUM ('Individual', 'Group');

CREATE TABLE public.performer (
  performer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  organization_id BIGINT REFERENCES public.organization(organization_id) ON DELETE SET NULL,

  name TEXT NOT NULL,
  type performer_type NOT NULL,
  description TEXT NOT NULL,
  position TEXT,
  avatar_url TEXT,
  cover_image_url TEXT NOT NULL,
  gallery_image_url_1 TEXT,
  gallery_image_url_2 TEXT,
  gallery_image_url_3 TEXT,
  gallery_image_url_4 TEXT,
  gallery_image_url_5 TEXT,

  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,

  CONSTRAINT performer_external_id_unique UNIQUE (id)
);
--------------------------------------------------------------------------------
-- Index
--------------------------------------------------------------------------------
CREATE INDEX idx_performer_organization_id ON public.performer (organization_id);

--------------------------------------------------------------------------------
-- TimeStamp
--------------------------------------------------------------------------------
CREATE TRIGGER set_timestamp 
  BEFORE UPDATE ON public.performer 
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_set_timestamp();

--------------------------------------------------------------------------------
-- RLS
--------------------------------------------------------------------------------
ALTER TABLE public.performer ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
  ON public.performer 
  FOR SELECT TO public USING (true);