--------------------------------------------------------------------------------
-- Event Table (イベント)
--------------------------------------------------------------------------------
CREATE TABLE public.event (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  venue_id BIGINT REFERENCES public.venue(venue_id) ON DELETE SET NULL,
  organization_id BIGINT REFERENCES public.organization(organization_id) ON DELETE SET NULL,

  title TEXT NOT NULL,
  overview_description TEXT,
  description TEXT,
  logo_url TEXT,
  cover_image_url TEXT,
  gallery_image_url_1 TEXT,
  gallery_image_url_2 TEXT,
  gallery_image_url_3 TEXT,

  display_order INT NOT NULL DEFAULT 999,

  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,

  CONSTRAINT event_external_id_unique UNIQUE (id)
);

--------------------------------------------------------------------------------
-- Index
--------------------------------------------------------------------------------
CREATE INDEX idx_event_display_order ON public.event (display_order);
CREATE INDEX idx_event_venue_id ON public.event (venue_id);
CREATE INDEX idx_event_organization_id ON public.event (organization_id);

--------------------------------------------------------------------------------
-- TimeStamp
--------------------------------------------------------------------------------
CREATE TRIGGER set_timestamp 
  BEFORE UPDATE ON public.event 
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_set_timestamp();

--------------------------------------------------------------------------------
-- RLS
--------------------------------------------------------------------------------
ALTER TABLE public.event ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
  ON public.event 
  FOR SELECT TO public USING (true);