--------------------------------------------------------------------------------
-- Organization Table (組織)
--------------------------------------------------------------------------------
CREATE TABLE public.organization (
  organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id UUID NOT NULL DEFAULT gen_random_uuid(),

  name TEXT NOT NULL,
  overview_description TEXT NOT NULL,
  description TEXT NOT NULL,
  logo_url TEXT NOT NULL,
  cover_image_url TEXT NOT NULL,
  gallery_image_url_1 TEXT,
  gallery_image_url_2 TEXT,
  gallery_image_url_3 TEXT,
  gallery_image_url_4 TEXT,
  gallery_image_url_5 TEXT,
  website_url TEXT,
  instagram_url TEXT,
  linkedin_url TEXT,
  x_url TEXT,
  youtube_url TEXT,

  display_order INT NOT NULL DEFAULT 999,

  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,

  CONSTRAINT organization_public_id_unique UNIQUE (id)
);

--------------------------------------------------------------------------------
-- Index
--------------------------------------------------------------------------------
CREATE INDEX idx_organization_display_order
ON public.organization (display_order);

--------------------------------------------------------------------------------
-- TimeStamp
--------------------------------------------------------------------------------
CREATE TRIGGER set_timestamp 
  BEFORE UPDATE ON public.organization 
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_set_timestamp();

--------------------------------------------------------------------------------
-- RLS
--------------------------------------------------------------------------------
ALTER TABLE public.organization ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access" 
  ON public.organization 
  FOR SELECT TO public USING (true);