-- update_at function
CREATE OR REPLACE FUNCTION update_at()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

REVOKE EXECUTE ON FUNCTION public.update_at FROM public;
GRANT EXECUTE ON FUNCTION public.update_at TO authenticated, service_role;
-- venues table
CREATE TABLE public.venues (
    venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    icon TEXT,
    capacity INTEGER,
    floor INTEGER,
    map_latitude DOUBLE PRECISION,
    map_longitude DOUBLE PRECISION,
    is_primary BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_venue_display_order ON public.venues(display_order DESC);

-- trigger
CREATE TRIGGER update_venues
    BEFORE UPDATE ON public.venues
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.venues FOR ALL USING (false);
REVOKE ALL ON public.venues FROM public;
-- organizations table
CREATE TABLE public.organizations (
    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    icon TEXT,
    sponsor TEXT,
    description TEXT,
    header_image TEXT,
    images TEXT[] DEFAULT '{}',

    website TEXT,
    instagram TEXT,
    linkedin TEXT,
    twitter TEXT,
    youtube TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_organization_display_order ON public.organizations(display_order DESC);

-- trigger
CREATE TRIGGER update_organizations
    BEFORE UPDATE ON public.organizations
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.organizations FOR ALL USING (false);
REVOKE ALL ON public.organizations FROM public;
-- tags table
CREATE TABLE public.tags (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_tag_display_order ON public.tags(display_order DESC);

-- trigger
CREATE TRIGGER update_tags
    BEFORE UPDATE ON public.tags
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.tags FOR ALL USING (false);
REVOKE ALL ON public.tags FROM public;
-- slots table
CREATE TABLE public.slots (
    slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    starts TIME(0) NOT NULL,
    ends TIME(0) NOT NULL,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_slot_display_order ON public.slots(display_order DESC);

-- trigger
CREATE TRIGGER update_slots
    BEFORE UPDATE ON public.slots
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.slots FOR ALL USING (false);
REVOKE ALL ON public.slots FROM public;
-- performers table
CREATE TABLE public.performers (
    performer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performer_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    affiliation TEXT,
    icon TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_performer_display_order ON public.performers(display_order DESC);

-- trigger
CREATE TRIGGER update_performers
    BEFORE UPDATE ON public.performers
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.performers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.performers FOR ALL USING (false);
REVOKE ALL ON public.performers FROM public;
-- categories table
CREATE TABLE public.categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    icon TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_category_display_order ON public.categories(display_order DESC);

-- trigger
CREATE TRIGGER update_categories
    BEFORE UPDATE ON public.categories
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.categories FOR ALL USING (false);
REVOKE ALL ON public.categories FROM public;
-- foods table
CREATE TABLE public.foods (
    food_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    description TEXT,
    icon TEXT,
    minutes INTEGER,
    distance INTEGER,
    address TEXT,
    website TEXT,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_foods_display_order ON public.foods(display_order DESC);

-- trigger
CREATE TRIGGER update_foods
    BEFORE UPDATE ON public.foods
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.foods ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.foods FOR ALL USING (false);
REVOKE ALL ON public.foods FROM public;
-- events table
CREATE TABLE public.events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    icon TEXT,
    description TEXT,
    header_image TEXT,
    images TEXT[] DEFAULT '{}',

    organization_id BIGINT REFERENCES public.organizations(organization_id),

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_event_organization_id ON public.events(organization_id);
CREATE INDEX idx_event_display_order ON public.events(display_order DESC);

-- trigger
CREATE TRIGGER update_events
    BEFORE UPDATE ON public.events
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events FOR ALL USING (false);
REVOKE ALL ON public.events FROM public;
-- features table
CREATE TABLE public.features (
    feature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feature_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    note TEXT,
    image TEXT,

    event_id BIGINT REFERENCES public.events(event_id),

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_features_event_id ON public.features(event_id);
CREATE INDEX idx_features_display_order ON public.features(display_order DESC);

-- trigger
CREATE TRIGGER update_features
    BEFORE UPDATE ON public.features
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.features ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.features FOR ALL USING (false);
REVOKE ALL ON public.features FROM public;
-- banners table
CREATE TABLE public.banners (
    banner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banner_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    image TEXT NOT NULL,
    link TEXT,

    event_id BIGINT REFERENCES public.events(event_id),

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_banners_event_id ON public.banners(event_id);
CREATE INDEX idx_banners_display_order ON public.banners(display_order DESC);

-- trigger
CREATE TRIGGER update_banners
    BEFORE UPDATE ON public.banners
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.banners FOR ALL USING (false);
REVOKE ALL ON public.banners FROM public;
-- news table
CREATE TABLE public.news (
    news_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    caption TEXT,
    description TEXT,
    header_image TEXT,
    thumbnail TEXT,
    website TEXT,

    performer_id BIGINT REFERENCES public.performers(performer_id),
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_news_performer_id ON public.news(performer_id);
CREATE INDEX idx_news_display_order ON public.news(display_order DESC);

-- trigger
CREATE TRIGGER update_news
    BEFORE UPDATE ON public.news
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.news FOR ALL USING (false);
REVOKE ALL ON public.news FROM public;
-- events_performers middle table
CREATE TABLE public.events_performers (
    event_performer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    performer_id BIGINT NOT NULL REFERENCES public.performers(performer_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_events_performers_unique_active 
ON public.events_performers(event_id, performer_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_events_performers_display_order ON public.events_performers(display_order DESC);
CREATE INDEX idx_events_performers_event_id ON public.events_performers(event_id);
CREATE INDEX idx_events_performers_performer_id ON public.events_performers(performer_id);

-- trigger
CREATE TRIGGER update_events_performers
    BEFORE UPDATE ON public.events_performers
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events_performers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events_performers FOR ALL USING (false);
REVOKE ALL ON public.events_performers FROM public;
-- events_slots middle table
CREATE TABLE public.events_slots (
    event_slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    slot_id BIGINT NOT NULL REFERENCES public.slots(slot_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_events_slots_unique_active 
ON public.events_slots(event_id, slot_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_events_slots_display_order ON public.events_slots(display_order DESC);
CREATE INDEX idx_events_slots_event_id ON public.events_slots(event_id);
CREATE INDEX idx_events_slots_slot_id ON public.events_slots(slot_id);

-- trigger
CREATE TRIGGER update_events_slots
    BEFORE UPDATE ON public.events_slots
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events_slots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events_slots FOR ALL USING (false);
REVOKE ALL ON public.events_slots FROM public;
-- events_tags middle table
CREATE TABLE public.events_tags (
    event_tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES public.tags(tag_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_events_tags_unique_active 
ON public.events_tags(event_id, tag_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_events_tags_display_order ON public.events_tags(display_order DESC);
CREATE INDEX idx_events_tags_event_id ON public.events_tags(event_id);
CREATE INDEX idx_events_tags_tag_id ON public.events_tags(tag_id);

-- trigger
CREATE TRIGGER update_events_tags
    BEFORE UPDATE ON public.events_tags
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events_tags ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events_tags FOR ALL USING (false);
REVOKE ALL ON public.events_tags FROM public;
-- events_venues middle table
CREATE TABLE public.events_venues (
    event_venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL REFERENCES public.events(event_id) ON DELETE CASCADE,
    venue_id BIGINT NOT NULL REFERENCES public.venues(venue_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_events_venues_unique_active 
ON public.events_venues(event_id, venue_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_events_venues_display_order ON public.events_venues(display_order DESC);
CREATE INDEX idx_events_venues_event_id ON public.events_venues(event_id);
CREATE INDEX idx_events_venues_venue_id ON public.events_venues(venue_id);

-- trigger
CREATE TRIGGER update_events_venues
    BEFORE UPDATE ON public.events_venues
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.events_venues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.events_venues FOR ALL USING (false);
REVOKE ALL ON public.events_venues FROM public;
-- tags_categories middle table
CREATE TABLE public.tags_categories (
    tag_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tag_id BIGINT NOT NULL REFERENCES public.tags(tag_id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES public.categories(category_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_tags_categories_unique_active 
ON public.tags_categories(tag_id, category_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_tags_categories_display_order ON public.tags_categories(display_order DESC);
CREATE INDEX idx_tags_categories_tag_id ON public.tags_categories(tag_id);
CREATE INDEX idx_tags_categories_category_id ON public.tags_categories(category_id);

-- trigger
CREATE TRIGGER update_tags_categories
    BEFORE UPDATE ON public.tags_categories
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.tags_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.tags_categories FOR ALL USING (false);
REVOKE ALL ON public.tags_categories FROM public;
-- venues_organizations middle table
CREATE TABLE public.venues_organizations (
    venue_organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    venue_id BIGINT NOT NULL REFERENCES public.venues(venue_id) ON DELETE CASCADE,
    organization_id BIGINT NOT NULL REFERENCES public.organizations(organization_id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE UNIQUE INDEX idx_venues_organizations_unique_active 
ON public.venues_organizations(venue_id, organization_id) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_venues_organizations_display_order ON public.venues_organizations(display_order DESC);
CREATE INDEX idx_venues_organizations_venue_id ON public.venues_organizations(venue_id);
CREATE INDEX idx_venues_organizations_organization_id ON public.venues_organizations(organization_id);

-- trigger
CREATE TRIGGER update_venues_organizations
    BEFORE UPDATE ON public.venues_organizations
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.venues_organizations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.venues_organizations FOR ALL USING (false);
REVOKE ALL ON public.venues_organizations FROM public;
-- mv_category_tree
DROP MATERIALIZED VIEW IF EXISTS public.mv_category_tree CASCADE;

CREATE MATERIALIZED VIEW public.mv_category_tree AS
WITH cte_tag_events AS (
    SELECT
        t.tag_id,
        t.tag_public_id,
        t.name,
        t.caption,
        COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'event_public_id', e.event_public_id,
                    'name',            e.name,
                    'caption',         e.caption,
                    'icon',            e.icon,
                    'display_order',   e.display_order
                ) ORDER BY e.display_order DESC, e.event_id
            ) FILTER (WHERE e.event_id IS NOT NULL),
            '[]'::jsonb
        ) AS events
    FROM public.tags t
    LEFT JOIN public.events_tags et ON t.tag_id = et.tag_id AND et.deleted_at IS NULL
    LEFT JOIN public.events e ON et.event_id = e.event_id AND e.deleted_at IS NULL
    WHERE t.deleted_at IS NULL
    GROUP BY t.tag_id, t.tag_public_id, t.name, t.caption
)

SELECT
    c.category_public_id,
    c.name,
    c.caption,
    c.icon,
    c.display_order AS category_display_order,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'tag_public_id', te.tag_public_id,
                'name',          te.name,
                'caption',       te.caption,
                'events',        te.events,
                'display_order', tc.display_order
            ) ORDER BY tc.display_order DESC, te.tag_id
        ) FILTER (WHERE te.tag_id IS NOT NULL),
        '[]'::jsonb
    ) AS tags

FROM public.categories c
LEFT JOIN public.tags_categories tc ON c.category_id = tc.category_id AND tc.deleted_at IS NULL
LEFT JOIN cte_tag_events te ON tc.tag_id = te.tag_id
WHERE c.deleted_at IS NULL
GROUP BY c.category_id, c.category_public_id, c.name, c.caption, c.icon, c.display_order;

-- indexes
CREATE UNIQUE INDEX idx_mv_category_tree_public_id ON public.mv_category_tree(category_public_id);
CREATE INDEX idx_mv_category_tree_display_order ON public.mv_category_tree(category_display_order DESC);

-- security
REVOKE ALL ON public.mv_category_tree FROM public, anon, authenticated;
-- mv_event_details
DROP MATERIALIZED VIEW IF EXISTS public.mv_event_details;

CREATE MATERIALIZED VIEW public.mv_event_details AS
WITH 
cte_venues AS (
    SELECT 
        ev.event_id,
        jsonb_agg(
            jsonb_build_object(
                'venue_public_id', v.venue_public_id,
                'name',            v.name,
                'display_order',   ev.display_order
            ) ORDER BY ev.display_order DESC, v.venue_id
        ) AS data
    FROM public.events_venues ev
    JOIN public.venues v ON ev.venue_id = v.venue_id
    WHERE ev.deleted_at IS NULL AND v.deleted_at IS NULL
    GROUP BY ev.event_id
),
cte_tags AS (
    SELECT 
        et.event_id,
        jsonb_agg(
            jsonb_build_object(
                'tag_public_id', t.tag_public_id,
                'name',          t.name,
                'display_order', et.display_order
            ) ORDER BY et.display_order DESC, t.tag_id
        ) AS data
    FROM public.events_tags et
    JOIN public.tags t ON et.tag_id = t.tag_id
    WHERE et.deleted_at IS NULL AND t.deleted_at IS NULL
    GROUP BY et.event_id
),
cte_slots AS (
    SELECT 
        es.event_id,
        jsonb_agg(
            jsonb_build_object(
                'slot_public_id', s.slot_public_id,
                'starts',         to_char(s.starts, 'HH24:MI'),
                'ends',           to_char(s.ends, 'HH24:MI'),
                'display_order',  es.display_order
            ) ORDER BY es.display_order DESC, s.slot_id
        ) AS data
    FROM public.events_slots es
    JOIN public.slots s ON es.slot_id = s.slot_id
    WHERE es.deleted_at IS NULL AND s.deleted_at IS NULL
    GROUP BY es.event_id
),
cte_performers AS (
    SELECT 
        ep.event_id,
        jsonb_agg(
            jsonb_build_object(
                'performer_public_id', p.performer_public_id,
                'name',                p.name,
                'affiliation',         p.affiliation,
                'icon',                p.icon,
                'display_order',       ep.display_order
            ) ORDER BY ep.display_order DESC, p.performer_id
        ) AS data
    FROM public.events_performers ep
    JOIN public.performers p ON ep.performer_id = p.performer_id
    WHERE ep.deleted_at IS NULL AND p.deleted_at IS NULL
    GROUP BY ep.event_id
)

SELECT
    e.event_public_id,
    e.header_image,
    e.icon,
    e.name,
    e.caption,
    e.description,
    e.images,
    
    jsonb_build_object(
        'organization_public_id', o.organization_public_id,
        'name',                   o.name,
        'caption',                o.caption,
        'icon',                   o.icon,
        'sponsor',                o.sponsor
    ) AS organization,

    COALESCE(v.data, '[]'::jsonb) AS venues,
    COALESCE(t.data, '[]'::jsonb) AS tags,
    COALESCE(s.data, '[]'::jsonb) AS slots,
    COALESCE(p.data, '[]'::jsonb) AS performers,

    e.display_order

FROM public.events e
LEFT JOIN public.organizations o ON e.organization_id = o.organization_id
LEFT JOIN cte_venues v ON e.event_id = v.event_id
LEFT JOIN cte_tags t ON e.event_id = t.event_id
LEFT JOIN cte_slots s ON e.event_id = s.event_id
LEFT JOIN cte_performers p ON e.event_id = p.event_id

WHERE e.deleted_at IS NULL;

-- indexes
CREATE UNIQUE INDEX idx_mv_event_details_public_id ON public.mv_event_details(event_public_id);
CREATE INDEX idx_mv_event_details_display_order ON public.mv_event_details(display_order DESC);
CREATE INDEX idx_mv_event_details_tags ON public.mv_event_details USING GIN (tags);

-- security
REVOKE ALL ON public.mv_event_details FROM public, anon, authenticated;
-- mv_venue_timeline
DROP MATERIALIZED VIEW IF EXISTS public.mv_venue_timeline CASCADE;

CREATE MATERIALIZED VIEW public.mv_venue_timeline AS
WITH cte_timeline AS (
    SELECT
        ev.venue_id,
        s.starts,
        jsonb_agg(
            jsonb_build_object(
                'event_public_id', e.event_public_id,
                'name',            e.name,
                'caption',         e.caption,
                'icon',            e.icon,
                'venue_name',      v.name,
                'starts',          to_char(s.starts, 'HH24:MI'),
                'ends',            to_char(s.ends, 'HH24:MI'),
                'display_order',   e.display_order
            ) ORDER BY e.display_order DESC, e.event_id
        ) AS events
    FROM public.events e
    JOIN public.events_venues ev ON e.event_id = ev.event_id AND ev.deleted_at IS NULL
    JOIN public.venues v ON ev.venue_id = v.venue_id AND v.deleted_at IS NULL
    JOIN public.events_slots es ON e.event_id = es.event_id AND es.deleted_at IS NULL
    JOIN public.slots s ON es.slot_id = s.slot_id AND s.deleted_at IS NULL
    WHERE e.deleted_at IS NULL
    GROUP BY ev.venue_id, s.starts, v.name
)

SELECT
    v.venue_public_id,
    v.name,
    v.icon,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'starts', to_char(t.starts, 'HH24:MI'),
                'events', t.events
            ) ORDER BY t.starts ASC
        ) FILTER (WHERE t.starts IS NOT NULL),
        '[]'::jsonb
    ) AS timeline

FROM public.venues v
LEFT JOIN cte_timeline t ON v.venue_id = t.venue_id
WHERE v.deleted_at IS NULL
GROUP BY v.venue_id, v.venue_public_id, v.name, v.icon;

-- indexes
CREATE UNIQUE INDEX idx_mv_venue_timeline_public_id ON public.mv_venue_timeline(venue_public_id);

-- security
REVOKE ALL ON public.mv_venue_timeline FROM public, anon, authenticated;
-- refresh_all_mvs

CREATE OR REPLACE FUNCTION refresh_all_mvs()
RETURNS void
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    -- 基礎MV（重い結合のみ維持）
    REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_event_details;

    -- 派生MV
    REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_venue_timeline;
    REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_category_tree;
END;
$$ LANGUAGE plpgsql;

REVOKE EXECUTE ON FUNCTION public.refresh_all_mvs FROM public;
-- get_banners

CREATE OR REPLACE FUNCTION get_banners()
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    RETURN COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'banner_public_id', b.banner_public_id,
                    'image',            b.image,
                    'link',             b.link,
                    'event_public_id',  e.event_public_id,
                    'display_order',    b.display_order
                ) ORDER BY b.display_order DESC, b.banner_id
            )
            FROM public.banners b
            LEFT JOIN public.events e ON b.event_id = e.event_id AND e.deleted_at IS NULL
            WHERE b.deleted_at IS NULL
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_banners() TO anon;
-- get_display_venue

CREATE OR REPLACE FUNCTION get_display_venue()
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    RETURN COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'venue_public_id', v.venue_public_id,
                    'name',            v.name,
                    'icon',            v.icon,
                    'capacity',        v.capacity,
                    'floor',           v.floor,
                    'map_latitude',    v.map_latitude,
                    'map_longitude',   v.map_longitude,
                    'display_order',   v.display_order
                ) ORDER BY v.display_order DESC, v.venue_id
            )
            FROM public.venues v
            WHERE v.is_primary = TRUE
            AND v.deleted_at IS NULL
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_display_venue() TO anon;
-- get_event_details

CREATE OR REPLACE FUNCTION get_event_details(event_public_id UUID DEFAULT NULL)
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    result JSONB;
BEGIN
    IF event_public_id IS NULL THEN
        RETURN NULL;
    END IF;

    SELECT row_to_json(mv)
    INTO result
    FROM public.mv_event_details mv
    WHERE mv.event_public_id = get_event_details.event_public_id;

    RETURN result;
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_event_details(UUID) TO anon;
-- get_events_by_tag

CREATE OR REPLACE FUNCTION get_events_by_tag(
    tag_public_id UUID DEFAULT NULL
)
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF tag_public_id IS NULL THEN
        RETURN '[]'::jsonb;
    END IF;

    RETURN COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'event_public_id', e.event_public_id,
                    'name',            e.name,
                    'caption',         e.caption,
                    'icon',            e.icon,
                    'display_order',   e.display_order
                ) ORDER BY e.display_order DESC, e.event_id
            )
            FROM public.tags t
            JOIN public.events_tags et ON t.tag_id = et.tag_id AND et.deleted_at IS NULL
            JOIN public.events e ON et.event_id = e.event_id AND e.deleted_at IS NULL
            WHERE t.tag_public_id = get_events_by_tag.tag_public_id
            AND t.deleted_at IS NULL
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_events_by_tag(UUID) TO anon;
-- get_events_by_venue

CREATE OR REPLACE FUNCTION get_events_by_venue(venue_public_id UUID DEFAULT NULL)
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF venue_public_id IS NULL THEN
        RETURN '[]'::jsonb;
    END IF;

    RETURN COALESCE(
        (
            SELECT mv.timeline
            FROM public.mv_venue_timeline mv
            WHERE mv.venue_public_id = get_events_by_venue.venue_public_id
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_events_by_venue(UUID) TO anon;
-- get_features

CREATE OR REPLACE FUNCTION get_features()
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    RETURN COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'feature_public_id', f.feature_public_id,
                    'name',              f.name,
                    'caption',           f.caption,
                    'note',              f.note,
                    'image',             f.image,
                    'event_public_id',   e.event_public_id,
                    'display_order',     f.display_order
                ) ORDER BY f.display_order DESC, f.feature_id
            )
            FROM public.features f
            LEFT JOIN public.events e ON f.event_id = e.event_id AND e.deleted_at IS NULL
            WHERE f.deleted_at IS NULL
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_features() TO anon;
-- get_news

CREATE OR REPLACE FUNCTION get_news()
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    RETURN COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'news_public_id', n.news_public_id,
                    'name',           n.name,
                    'caption',        n.caption,
                    'description',    n.description,
                    'header_image',   n.header_image,
                    'thumbnail',      n.thumbnail,
                    'website',        n.website,
                    'performer',      CASE 
                        WHEN p.performer_id IS NOT NULL THEN
                            jsonb_build_object(
                                'performer_public_id', p.performer_public_id,
                                'name',                p.name,
                                'affiliation',         p.affiliation,
                                'icon',                p.icon
                            )
                        ELSE NULL
                    END,
                    'display_order',  n.display_order
                ) ORDER BY n.display_order DESC, n.created_at DESC
            )
            FROM public.news n
            LEFT JOIN public.performers p ON n.performer_id = p.performer_id AND p.deleted_at IS NULL
            WHERE n.deleted_at IS NULL
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_news() TO anon;
-- get_several_events_by_tag

CREATE OR REPLACE FUNCTION get_several_events_by_tag()
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    RETURN COALESCE(
        (
            WITH cte_tag_events AS (
                SELECT
                    t.tag_id,
                    t.tag_public_id,
                    t.name,
                    t.caption,
                    t.display_order AS tag_display_order,
                    COALESCE(
                        jsonb_agg(
                            jsonb_build_object(
                                'event_public_id', e.event_public_id,
                                'name',            e.name,
                                'caption',         e.caption,
                                'icon',            e.icon,
                                'display_order',   e.display_order
                            ) ORDER BY e.display_order DESC, e.event_id
                        ) FILTER (WHERE e.event_id IS NOT NULL),
                        '[]'::jsonb
                    ) AS events
                FROM public.tags t
                LEFT JOIN public.events_tags et ON t.tag_id = et.tag_id AND et.deleted_at IS NULL
                LEFT JOIN public.events e ON et.event_id = e.event_id AND e.deleted_at IS NULL
                WHERE t.deleted_at IS NULL
                GROUP BY t.tag_id, t.tag_public_id, t.name, t.caption, t.display_order
            )
            SELECT jsonb_agg(
                jsonb_build_object(
                    'tag_public_id', te.tag_public_id,
                    'name',          te.name,
                    'caption',       te.caption,
                    'events',        (
                        SELECT COALESCE(jsonb_agg(ev), '[]'::jsonb)
                        FROM (
                            SELECT ev
                            FROM jsonb_array_elements(te.events) AS ev
                            LIMIT 4
                        ) AS limited_events
                    ),
                    'display_order', te.tag_display_order
                ) ORDER BY te.tag_display_order DESC
            )
            FROM cte_tag_events te
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_several_events_by_tag() TO anon;
-- get_tag_and_events_by_category

CREATE OR REPLACE FUNCTION get_tag_and_events_by_category(
    category_public_id UUID DEFAULT NULL
)
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF category_public_id IS NULL THEN
        RETURN '[]'::jsonb;
    END IF;

    RETURN COALESCE(
        (
            SELECT mv.tags
            FROM public.mv_category_tree mv
            WHERE mv.category_public_id = get_tag_and_events_by_category.category_public_id
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_tag_and_events_by_category(UUID) TO anon;
-- get_venue_details

CREATE OR REPLACE FUNCTION get_venue_details(venue_public_id UUID DEFAULT NULL)
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    result JSONB;
BEGIN
    IF venue_public_id IS NULL THEN
        RETURN NULL;
    END IF;

    WITH cte_organizations AS (
        SELECT 
            vo.venue_id,
            jsonb_agg(
                jsonb_build_object(
                    'organization_public_id', o.organization_public_id,
                    'name',                   o.name,
                    'icon',                   o.icon,
                    'display_order',          vo.display_order
                ) ORDER BY vo.display_order DESC, o.organization_id
            ) AS data
        FROM public.venues_organizations vo
        JOIN public.organizations o ON vo.organization_id = o.organization_id
        WHERE vo.deleted_at IS NULL AND o.deleted_at IS NULL
        GROUP BY vo.venue_id
    )
    SELECT jsonb_build_object(
        'venue_public_id', v.venue_public_id,
        'name',            v.name,
        'icon',            v.icon,
        'map_latitude',    v.map_latitude,
        'map_longitude',   v.map_longitude,
        'is_primary',      v.is_primary,
        'organizations',   COALESCE(o.data, '[]'::jsonb)
    )
    INTO result
    FROM public.venues v
    LEFT JOIN cte_organizations o ON v.venue_id = o.venue_id
    WHERE v.venue_public_id = get_venue_details.venue_public_id
    AND v.deleted_at IS NULL;

    RETURN result;
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_venue_details(UUID) TO anon;
-- get_categories

CREATE OR REPLACE FUNCTION get_categories()
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    RETURN COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'category_public_id', b.category_public_id,
                    'name',            b.name,
                    'icon',             b.icon,
                    'display_order',    b.display_order
                ) ORDER BY b.display_order DESC, b.category_id
            )
            FROM public.categories b
            WHERE b.deleted_at IS NULL
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.get_categories() TO anon;
