-- rankings
CREATE TABLE IF NOT EXISTS public.rankings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_public_id UUID NOT NULL REFERENCES public.events(event_public_id) ON DELETE CASCADE,
    rank INTEGER NOT NULL,
    score INTEGER NOT NULL,
    type TEXT NOT NULL, -- 'top' or 'trending'
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(event_public_id, type)
);

-- indexes
CREATE INDEX idx_rankings_event_public_id ON public.rankings(event_public_id);
CREATE INDEX idx_rankings_type_rank ON public.rankings(type, rank);

-- security
ALTER TABLE public.rankings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.rankings FOR ALL USING (false);
REVOKE ALL ON public.rankings FROM public;
GRANT ALL ON public.rankings TO service_role;



-- get_all_event_names
CREATE OR REPLACE FUNCTION get_all_event_names()
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    RETURN COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'event_public_id', e.event_public_id,
                    'name',            e.name
                ) ORDER BY e.name ASC
            )
            FROM public.events e
            WHERE e.deleted_at IS NULL
            AND e.event_public_id IS NOT NULL
        ),
        '[]'::jsonb
    );
END;
$$ LANGUAGE plpgsql;

-- security
GRANT EXECUTE ON FUNCTION public.get_all_event_names() TO anon, authenticated;



-- get_event_rankings
CREATE OR REPLACE FUNCTION get_event_rankings()
RETURNS JSONB
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  top_rankings JSONB;
  trending_rankings JSONB;
BEGIN

  -- Get Top Rankings
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'rank',            r.rank,
        'score',           r.score,
        'event_public_id', e.event_public_id,
        'name',            e.name,
        'caption',         e.caption,
        'icon',            e.icon
      ) ORDER BY r.rank ASC
    ),
    '[]'::jsonb
  ) INTO top_rankings
  FROM public.rankings r
  JOIN public.events e ON r.event_public_id = e.event_public_id
  WHERE r.type = 'top'
  AND e.deleted_at IS NULL
  AND e.event_public_id IS NOT NULL;

  -- Get Trending Rankings
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'rank',            r.rank,
        'score',           r.score,
        'event_public_id', e.event_public_id,
        'name',            e.name,
        'caption',         e.caption,
        'icon',            e.icon
      ) ORDER BY r.rank ASC
    ),
    '[]'::jsonb
  ) INTO trending_rankings
  FROM public.rankings r
  JOIN public.events e ON r.event_public_id = e.event_public_id
  WHERE r.type = 'trending'
  AND e.deleted_at IS NULL
  AND e.event_public_id IS NOT NULL;

  RETURN jsonb_build_object(
    'top',      top_rankings,
    'trending', trending_rankings
  );
END;
$$ LANGUAGE plpgsql;

-- security
GRANT EXECUTE ON FUNCTION public.get_event_rankings() TO anon, authenticated;