-- types
CREATE TYPE public.operational_status_type AS ENUM ('公開中', '準備中', '終了');
CREATE TYPE public.congestion_status_type AS ENUM ('余裕あり', 'やや混雑', '混雑', '制限中');
CREATE TYPE public.entry_type AS ENUM ('自由入場', '整理券配布', '予約制');

-- venues table
CREATE TABLE public.venues (
    venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    icon TEXT,
    capacity INTEGER,
    floor INTEGER,
    map_latitude DOUBLE PRECISION,
    map_longitude DOUBLE PRECISION,
    is_primary BOOLEAN DEFAULT FALSE,

    operational_status operational_status_type NOT NULL DEFAULT '準備中',
    congestion_status congestion_status_type NOT NULL DEFAULT '余裕あり',
    entry_type entry_type NOT NULL DEFAULT '自由入場',

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_venue_display_order ON public.venues(display_order DESC);

-- trigger
CREATE TRIGGER update_venues
    BEFORE UPDATE ON public.venues
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.venues FOR ALL USING (false);
REVOKE ALL ON public.venues FROM public;