-- venues table
CREATE TABLE public.venues (
    venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_public_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0,

    name TEXT NOT NULL,
    icon TEXT,
    capacity INTEGER,
    floor INTEGER,
    map_latitude DOUBLE PRECISION,
    map_longitude DOUBLE PRECISION,
    is_primary BOOLEAN DEFAULT FALSE,

    operational_status TEXT DEFAULT '準備中',
    congestion_status TEXT DEFAULT '余裕あり',
    entry_type TEXT DEFAULT '自由入場',

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- indexes
CREATE INDEX idx_venue_display_order ON public.venues(display_order DESC);

-- trigger
CREATE TRIGGER update_venues
    BEFORE UPDATE ON public.venues
    FOR EACH ROW
    EXECUTE FUNCTION update_at();

-- security
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "No direct access" ON public.venues FOR ALL USING (false);
REVOKE ALL ON public.venues FROM public;




-- constraints
ALTER TABLE public.venues ADD CONSTRAINT check_operational_status 
    CHECK (operational_status IN ('公開中', '準備中', '終了'));

ALTER TABLE public.venues ADD CONSTRAINT check_congestion_status 
    CHECK (congestion_status IN ('余裕あり', 'やや混雑', '混雑', '制限中'));

ALTER TABLE public.venues ADD CONSTRAINT check_entry_type 
    CHECK (entry_type IN ('自由入場', '整理券配布', '予約制'));